### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe22",
  "email": "some@email.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-0922"
}
###